services:
  - docker

matrix:
  include:
    - os: windows
      language: bash
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install: choco install python
      before_script: docker build -t docker_check:latest -f Dockerfile.win .

install: pip install pytest
before_script:
  - ./docker_build.sh
script:
  - pytest
